# Generated by Django 5.2.8 on 2025-11-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingprogram',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='programs_pdfs/'),
        ),
    ]
